import type { GamePreset } from '@archess/shared'

const classicPreset: GamePreset = {
  id: 'classic',
  name: 'Classic Archess',
  description: 'A standard 8x8 game with classic fantasy units.',
  arenaWidth: 800,
  arenaHeight: 600,
  board: {
    width: 8,
    height: 8,
    tileDefinitions: {
      grass: { id: 'grass', name: 'Grass', isWalkable: true },
      forest: { id: 'forest', name: 'Forest', isWalkable: true, movementCost: 2 },
      mountain: { id: 'mountain', name: 'Mountain', isWalkable: false },
      power_point: { id: 'power_point', name: 'Power Point', isWalkable: true },
    },
    layout: [
      ['grass', 'grass', 'forest', 'mountain', 'mountain', 'forest', 'grass', 'grass'],
      ['grass', 'power_point', 'grass', 'forest', 'forest', 'grass', 'power_point', 'grass'],
      ['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
      ['forest', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'forest'],
      ['forest', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'forest'],
      ['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
      ['grass', 'power_point', 'grass', 'forest', 'forest', 'grass', 'power_point', 'grass'],
      ['grass', 'grass', 'forest', 'mountain', 'mountain', 'forest', 'grass', 'grass'],
    ],
    player1StartPositions: {
      knight: { x: 3, y: 3 },
      archer: { x: 4, y: 2 },
      wizard: { x: 2, y: 0 },
    },
    player2StartPositions: {
      goblin: { x: 7, y: 7 },
      orc: { x: 3, y: 4 },
      shaman: { x: 4, y: 3 },
    },
  },
  units: {
    // --- Player 1 Units --- 
    knight: {
      id: 'knight',
      name: 'Knight',
      description: 'A sturdy melee fighter.',
      maxHp: 100,
      movementSpeed: 150,
      combatSpeed: 100,
      movement: { type: 'walk', distance: 3 },
      combatAbilities: [
        { 
          id: 'sword_swing', 
          name: 'Sword Swing', 
          description: 'A basic melee attack.', 
          type: 'attack', 
          attackType: 'melee', 
          damage: 15, 
          range: 35,
          cooldown: 1500,
          swingDuration: 500,
        },
        { 
          id: 'returning_axe', 
          name: 'Returning Axe', 
          description: 'Throws an axe that returns.', 
          type: 'attack', 
          attackType: 'boomerang_projectile',
          damage: 12,
          range: 150,
          cooldown: 6000,
          projectileSpeed: 180,
          projectileVisualKey: 'axe_spin',
          maxHitsPerUnit: 2,
        },
        {
          id: 'throwing_knife',
          name: 'Throwing Knife',
          description: 'A quick projectile attack.', 
          type: 'attack',
          attackType: 'direct_projectile',
          damage: 8,
          range: 400,
          cooldown: 2000,
          projectileSpeed: 300,
          projectileVisualKey: 'knife',
        },
        {
          id: 'holy_grenade',
          name: 'Holy Grenade',
          description: 'Lob a grenade that explodes.', 
          type: 'attack',
          attackType: 'aoe_projectile',
          damage: 10,
          range: 250,
          cooldown: 8000,
          projectileSpeed: 90,
          projectileVisualKey: 'grenade',
          aoeRadius: 70,
          aoeDuration: 5000,
          aoeDamagePerTick: 0,
        }
      ],
      strategyAbilities: [],
      cost: 10,
      hitboxRadius: 12,
    },
    archer: {
      id: 'archer',
      name: 'Archer',
      description: 'Ranged attacker.',
      maxHp: 70,
      movementSpeed: 180,
      combatSpeed: 100,
      movement: { type: 'walk', distance: 3 },
      combatAbilities: [
        { 
          id: 'arrow_shot', 
          name: 'Arrow Shot', 
          description: 'A standard ranged arrow attack.', 
          type: 'attack', 
          attackType: 'direct_projectile',
          damage: 10,
          range: 400,
          cooldown: 1200,
          projectileSpeed: 250,
          projectileVisualKey: 'arrow',
        },
      ],
      cost: 8,
      hitboxRadius: 8,
    },
    wizard: {
      id: 'wizard',
      name: 'Wizard',
      description: 'Powerful spellcaster (Champion).',
      maxHp: 60,
      movementSpeed: 120,
      combatSpeed: 100,
      movement: { type: 'walk', distance: 2 },
      combatAbilities: [
        { 
          id: 'fireball', 
          name: 'Fireball', 
          description: 'Hurls a ball of fire.', 
          type: 'attack',
          attackType: 'direct_projectile',
          damage: 25,
          range: 350,
          cooldown: 2500,
          projectileSpeed: 180,
          projectileVisualKey: 'fireball',
        },
        { 
          id: 'fire_bomb_aoe', 
          name: 'Fire Bomb', 
          description: 'Launches a bomb that explodes on impact, burning the area.', 
          type: 'attack',
          attackType: 'aoe_projectile',
          damage: 15,
          range: 300,
          cooldown: 8000,
          projectileSpeed: 100,
          projectileVisualKey: 'fire_bomb',
          aoeRadius: 60,
          aoeDuration: 4000,
          aoeDamagePerTick: 5,
        },
        { 
          id: 'teleport_short', 
          name: 'Short Teleport', 
          description: 'Blinks a short distance.', 
          type: 'movement',
          cooldown: 5000,
          strategyRange: 200,
        }, 
      ],
      cost: 15,
      hitboxRadius: 8,
    },
    // --- Player 2 Units ---
    goblin: {
      id: 'goblin',
      name: 'Goblin',
      description: 'Weak but numerous.',
      maxHp: 50,
      movementSpeed: 210,
      combatSpeed: 100,
      movement: { type: 'walk', distance: 3 },
      combatAbilities: [
        { 
          id: 'shiv', 
          name: 'Shiv', 
          description: 'A quick stab with a pointy object.', 
          type: 'attack', 
          attackType: 'melee',
          damage: 8,
          range: 30,
          cooldown: 1000, // ms
          swingDuration: 400, // ms
        },
      ],
      cost: 5,
      hitboxRadius: 7,
    },
    orc: {
      id: 'orc',
      name: 'Orc',
      description: 'Tough melee brute.',
      maxHp: 120,
      movementSpeed: 120,
      combatSpeed: 100,
      movement: { type: 'walk', distance: 3 },
      combatAbilities: [
        { 
          id: 'axe_chop', 
          name: 'Axe Chop', 
          description: 'A heavy swing with an axe.', 
          type: 'attack', 
          attackType: 'melee',
          damage: 18,
          range: 45, // Adjusted range
          cooldown: 1800, // ms
          swingDuration: 700, // ms
        },
      ],
      cost: 12,
      hitboxRadius: 15,
    },
    shaman: {
      id: 'shaman',
      name: 'Shaman',
      description: 'Healer and disruptor (Champion).',
      maxHp: 70,
      movementSpeed: 150,
      combatSpeed: 100,
      movement: { type: 'walk', distance: 2 },
      combatAbilities: [
        { 
          id: 'spirit_bolt', 
          name: 'Spirit Bolt', 
          description: 'Fires a weak bolt of spirit energy.', 
          type: 'attack', 
          attackType: 'direct_projectile',
          damage: 10,
          range: 350,
          cooldown: 1500, // ms
          projectileSpeed: 160,
          projectileVisualKey: 'spirit_bolt',
        },
        { 
          id: 'curse', 
          name: 'Curse', 
          description: 'Slows target movement speed.', 
          type: 'support', 
          cooldown: 4000, // ms
          attackType: 'direct_projectile', 
          range: 300,
          projectileSpeed: 150,
          projectileVisualKey: 'curse',
        },
        { 
          id: 'heal_minor', 
          name: 'Minor Heal', 
          description: 'Restores a small amount of health.', 
          type: 'support', 
          cooldown: 3000, // ms
          strategyRange: 250, // Use strategyRange for cast range? Or add specific 'castRange'?
          healAmount: 20, // Add specific property for heal amount
        }, 
      ],
      cost: 14,
      hitboxRadius: 9,
    },
    // Add more units for both sides...
  },
  winConditions: [
    { type: 'eliminate_all' },
    { type: 'eliminate_champion', championUnitTypeId: 'wizard' },
    { type: 'eliminate_champion', championUnitTypeId: 'shaman' },
    // { type: 'capture_points', capturePointTileIds: ['power_point'], pointsToWin: 2 }
  ],
}

// Export the preset object
export default classicPreset;
// Or use: export const preset = classicPreset; 